### ISSUE TITLE
Splitting parsing and dispatching?

### ISSUE THREAD

**Issue by Danack** [minicli/minicli#18]
Hi,

This is a nice little library. Before I spend too much time creating a pull request for it, I wanted to check if something is likely to be acceptable for the project or not.

How likely is it that a PR that splits the parsing + dispatching into separate steps would be accepted? This avoids the problem of needing to construct the complete dependency tree for commands.

I've previously implemented this for the symfony console tool, but as it "only benefited people outside of the Symfony ecosystem", it was rejected: github . com/symfony/symfony/issues/11974 . 

I've been using a fork of the symfony console tool since then, but it is quite 'big' 
https://github.com/danack/console

What's the chances of something like this being acceptable?

Below is an example of what it looks like when using it in.

```
$helloWorldCallable = function ($name) {
    echo "Hello world, and particularly $name".PHP_EOL;
};

// Create a command that will call the closure
$callableCommand = new Command($helloWorldCallable, 'greet');
$callableCommand->addArgument('name', InputArgument::REQUIRED, 'The name of the person to say hello to.');
$app->add($callableCommand);

$parsedCommand = $app->parseCommandLine();

$injector = new Auryn\Injector();
$injector->execute(
    $parsedCommand->getCallable(),
    $parsedCommand->getParams()
);
```

**Comment by erikaheidi** [comment]
Hello @Danack ! First of all, thanks for taking the time to suggest this idea! And I'm sorry I didn't reply earlier, it's been a couple busy weeks :)

Even though I can understand that this approach could bring some benefits, I worry about making it a lot more complex to create commands, which would go against the idea of simplicity that I would like to stick to in this project. I don't feel particularly inclined to have commands defined as entities with strict arguments like the big frameworks do. My initial vision was to have commands defined in a very similar way to web controllers, where you typically are free to check for parameters and respond accordingly, and creating a new command is just a matter of creating a new class implementing an interface (or just defining a callable directly in the app bootstrap code).

I don't fully grasp the problem with having the dependency tree for the commands loaded in the App class, considering the command is lazy loaded.

**Comment by syntaxseed** [comment]
I agree with keeping things simple. Unless this framework was planning to get much bigger, which I think it's pretty stable right now (?).

**Comment by Danack** [comment]
> I don't fully grasp the problem 

By having the parsing and dispatching linked together, it seems inevitable that the project will go down a route that will could be regrettable.

* commands having to be aware of the minicli project. I have strong opinions that the vast majority of code shouldn't be tied to the thing that is running it. Both to make it easier to test, as well as to eventually migrate to a new way of running it.

* not being able to use the same config system for both CLI and web applications. I prefer to have a single way of setting config for all the different environments my code runs in.

* having to use a service locator somewhere, which is fine in some circumstances, but I prefer to if possible. 

> I worry about making it a lot more complex to create commands,

Oh, I didn't mean to say that creating commands would be more difficult. Though the example may have given that impression.

I created two draft pull requests, to show what I was meaning. I don't full grok the ControllerInterface so the PRs might need polishing for those.

Draft PR for parsing commands: https://github.com/minicli/minicli/pull/21
Draft PR for allowing injecting of invoker: https://github.com/minicli/minicli/pull/22

They both accomplish the same thing....allowing people to use their own system for executing the code (and so being able to do dependency injection/config however they like, rather than it being part of the framework running the code.

> I don't feel particularly inclined to have commands defined as entities with strict arguments like the big frameworks do.

I totally agree with that, but more for the reason that error handling of missing/invalid variables should be done inside the command code, rather than at the framework level

Feel free to close if you don't think this is a path you want your project to take.

**Comment by erikaheidi** [comment]
I appreciate your input and advice, but for now I would like to keep it simple for pedagogic reasons. At this moment, I would advice anyone wanting to build bigger things to look for a framework with Console support like Laravel or Symfony.
