### ISSUE TITLE
Php 8 support

### ISSUE THREAD

**Issue by Wulfheart** [minicli/minicli#26]

**Comment by erikaheidi** [comment]
Thanks for the suggestion, I will take a look at that soon-_ish_.

**Comment by erikaheidi** [comment]
What exactly do you mean? I just run all tests in PHP 8.03 and there seems to be no issues. Unless you have an example of problem regarding Minicli on PHP 8, I don't get what you mean? Could you elaborate?

**Comment by erikaheidi** [comment]
![Screenshot from 2021-03-23 13-22-06](https://user-images.githubusercontent.com/293241/112145776-161c8a80-8bdb-11eb-9545-0479ca91ad9c.png)

**Comment by Wulfheart** [comment]
Puh... I can't remember. I should have elaborated more. Sorry about that.
