### ISSUE TITLE
App default NULL config throws a warning 

### ISSUE THREAD

**Issue by lotfio** [minicli/minicli#3]
using the example given in the README.md to start minicli.  I had the following error:
 
![image](https://user-images.githubusercontent.com/18489496/82841829-c6e0cd00-9ed7-11ea-87f8-0624312e3aa6.png)

This is because you are appending a null to the config array by default and no config is passed when instantiating. 

![image](https://user-images.githubusercontent.com/18489496/82841953-1f17cf00-9ed8-11ea-8000-d4c2a35bbe9e.png)

using an empty array as a default value solves the problem and suites better as the type hint is an array 

![image](https://user-images.githubusercontent.com/18489496/82842257-1b387c80-9ed9-11ea-81e7-0623b8b01109.png)

**Comment by erikaheidi** [comment]
hey @lotfio , you're right! Thanks for flagging that. Would you like to send a PR? I can totally understand if you don't have time right now, just let me know :) I just want to make sure I give space for people to collaborate if they want!

cheers :)

**Comment by erikaheidi** [comment]
Hey! As this is really breaking stuff, I will give it a go now so I can get it fixed before sharing the new documentation website. I would like to welcome you, thou, to stick around and maybe contribute with some other issue you might probably find later :D

**Comment by lotfio** [comment]
I was about to pull :) thanks for your feedback anyways.
i would suggest adding a **CONTRIBUTE.md**  to clarify some contribution guidelines thanks

**Comment by erikaheidi** [comment]
That's a great suggestion, thank you! Will do that.
