### ISSUE TITLE
[Suggestion] Allow using Anonymous functions (Closure) as a Service (A la Pimple)

### ISSUE THREAD

**Issue by rkkoszewski** [minicli/minicli#35]
This is not a bug, just a suggestion for the "addService" feature. 

It would be great if it would be possible to register anonymous functions (Closures I believe it's called in PHP) as a Service. That way the whole class gets instantiated when the service is first accessed. I'm not sure if the current extension method its more or less efficient than the anonymous function method, but both can definitely coexist. The anonymous function is especially useful when you want to extend a class or instantiate the class with parameters on runtime.

I have this already working by extending App:

```
<?php
class DynamicApp extends \Minicli\App
{
    /**
     * @param $name
     * @param Closure $service
     */
    public function addAService($name, \Closure $service)
    {
        $this->services[$name] = $service;
    }

    /**
     * @param string $name
     */
    public function loadService($name)
    {
        if($this->services[$name] instanceof \Closure){
            $this->services[$name] = $this->services[$name]();
            $this->loaded_services[$name] = true;
        }else{
            parent::loadService($name);
        }
    }
}
```

This can then be used with anonymous functions like this:

```
$settings = [];
$app = new DynamicApp();
$app->addAService('database', function () use ($settings) {
    return new Medoo($settings);
});
```

Not sure if this is in scope for Minicli, but perhaps it would be interesting to have such functionality directly as part of App (Without the "A" in "addAService").
Hope somebody finds this useful, and thanks for the cool project!

**Comment by AbdelrhmanSaid** [comment]
You need to use a dependency injection container, there's a lot of great choices like `illuminate/container` or `DependencyInjection` component from symfony.

but if you need something minimal, I just created one from [here](https://github.com/redot-src/php-container), you can use it something like that.

```php

$settings = [];

$container = new Container();
$container->bind(Medoo::class, function () use ($settings) {
    return new Medoo($settings);
});
```
or just use an arrow function
```php
$container->bind(Medoo::class, fn() => new Medoo($settings));
```

**Comment by erikaheidi** [comment]
Hello @rkkoszewski , thank you for your suggestion and apologies for the very late reply. I think that is a good idea, would you like to implement it and send a PR? Thank  you once again!

**Comment by erikaheidi** [comment]
This is great, thank you and apologies for the delay in merging. I will be tagging a new release today.
