### ISSUE TITLE
PHP version conflict with PHPunit for development

### ISSUE THREAD

**Issue by lotfio** [minicli/minicli#4]
minicli is requiring a PHP version that is **>= 7.2** while **PHPunit 9** requires  at least version **7.3**  which is causing dependencies conflict as follow :

![image](https://user-images.githubusercontent.com/18489496/82920198-496c9980-9f77-11ea-88e6-5dcc8f8760d0.png)

This is caused only in **development**  when you run composer install or composer update (you won't see this error if you require minicli as package).

**Comment by syntaxseed** [comment]
This looks like a problem between your environment and phpunit. You can always downgrade the version of phpunit asked for in the composer.json. But I don't think minicli should be using anything but the latest version by default. (just my opinion)

**Comment by lotfio** [comment]
Yes it is an environment problem, actually i did that on purpose because i know that **pest** and **phpunit** use php 7.3 while minicli accepts php 7.2 which causes the problem .
so :
- using php 7.3 in development and allowing lower versions in production like php 7.2 
 may cause some **problems**  for example if we use `is_countable` builtin function which exists in php 7.3 but doesn't exists in php7.2 . there are some other features here [new in php 7.3](https://stitcher.io/blog/new-in-php-73)

- downgrading phpunit will cause **pest** not to work as it requires phpunit 9, in addition it will lead to different development environments (one contributer is using phpunit 8 with php 7.2 another one is using phpunit 9 with 7.3 which will absolutely cause so many problems).

in my opinion locking **minicli to php >= 7.3** would be the safest solution.

**Comment by syntaxseed** [comment]
7.2 is still officially supported though.

**Comment by syntaxseed** [comment]
Granted... I look at minicli as a framework & I often tweak the root composer.json for frameworks for things like this. :D

**Comment by syntaxseed** [comment]
There's no good solution here.
Either minicli doesn't support a legit version of PHP that is still popular. Or... it uses an older version of PHPUnit.

If I had to choose I'd prefer the latter.

Or a note in the docs to adjust the phpunit version if you are on 7.2. 🤔

**Comment by erikaheidi** [comment]
Thank y'all for bringing this up and giving all this very valuable feedback! It's complicated. 

Pest was the only way I was able to write those damn tests, I really like it and I think it's going to get really popular soon. I can't bump down the requirement for dev, and at the same time I wanted the minimal requirements for the regular user who is not developing for minicli, but just want to use it with `composer require`. It's complicated!

I guess you both agreed that there must be a unique PHP version requirement, isn't that right? In that case we will have to go for `7.3`, I can't see another way... :/

**Comment by lotfio** [comment]
Yes ! i would vote for 7.3

**Comment by erikaheidi** [comment]
@lotfio would you like to PR this change? :) This time I'll wait, I promise :D

**Comment by lotfio** [comment]
@erikaheidi  sure  :smiley:

**Comment by syntaxseed** [comment]
I would have voted for requiring an older version of phpunit that supports php 7.2.
But looks like you folks decided. No prob. :)

**Comment by erikaheidi** [comment]
@syntaxseed I totally get it, I would like that too at first, however we need the newer phpunit to use Pest, and using this testing framework will make things a lot easier in the long run! I really liked the experience of using Pest, it took me a few days to get to 98% coverage - of course that doesn't tell much, minicli still have bugs, but I think this will facilitate both for us and for others who want to contribute in the future :heart:

**Comment by syntaxseed** [comment]
Aaah that makes sense. Sounds good!
