### ISSUE TITLE
[Suggestion] : Add Dracula Color Theme

### ISSUE THREAD

**Issue by NicolasPereira** [minicli/minicli#44]
Hello everyone, everything good?
I liked the project and wanted to contribute by adding a `CLI-Theme`!
The inspiration would be Dracula's color palette, as it is a theme very accepted by developers in their IDE and code editors!

I found this material with the colors, https://draculatheme.com/contribute

If the idea is accepted, can I work on this implementation and open a PR?

Thanks

**Comment by erikaheidi** [comment]
Hello @NicolasPereira ! That's a great idea, can't wait for your PR :) go for it!

**Comment by AbdelrhmanSaid** [comment]
Check this PR #50

**Comment by erikaheidi** [comment]
Finally merged it, thank you :D
