### ISSUE TITLE
[RFC]: Support a wildcard/front controller

### ISSUE THREAD

**Issue by cspray** [minicli/minicli#46]
## Problem

There are situations where it could be useful to have a single controller that is used when a command _and_ a sub-command is provided. For example, in the `minicli/command-help` repo it might be helpful to be able to run:

```
./minicli help my-command
```

And retrieve help information specific to that command. From my understanding, it would not currently be possible to achieve something like this without creating the commands in the help namespace ahead of time. There are likely other use cases for this type of functionality where the command is a meta-command and does not know the various subcommands ahead of time.

## Solution

Add a wildcard or front controller that is used if a controller is not found. For example, given the following app structure:

```
/app
    /Command
       /Demo
           DefaultController.php
           FooController.php
           WildcardController.php
```

I'd expect the following commands to work properly.

```
./minicli demo                  # invokes the DefaultController
./minicli demo foo              # Invokes the FooController
./minicli demo bar              # Invokes the WildcardController
./minicli demo anythingElse     # Invokes the WildcardController
```

## Implementation

Given my lack of experience with the codebase I may be missing something. However, I believe that this could be achieved by adjusting the `App::runCommand`. Specifically, where [the controller is fetched](https://github.com/minicli/minicli/blob/e605a3c7fa80b89c58050044e033874c1d449771/src/App.php#L224-L226) also check for the null state and do a fallback check with a call to:

```
$controller = $this->commandRegistry->getCallableController($input->command, 'wildcard');
```

## Concerns

From my perspective there are 2 primary concerns with this approach:

1. It is kinda magical. It might not be obvious what is going on and I tend to avoid "magical" things.
2. It could conflict with existing controllers already named "WildcardController".

To solve both of these concerns we could add a new configuration to the `App` that explicitly toggles the wildcard functionality off or on, with a default to off to maintain backwards compatibility. It might be possible to do this on a per-namespace basis, however that seems to be more complex and I'm not sure how easily it could be implemented versus a "global" option.

---

I don't mind doing the work to test this out properly and actually implement it. However, before I started writing code I wanted to make sure that this is something the maintainers are open to including. If not I'll start thinking about alternative solutions for some of the problems I'm considering.

Thanks in advance for considering my suggestion!

**Comment by JustSteveKing** [comment]
Hey @cspray - are you still interested in this issue? I'm happy to start a conversation around it to see what could be done.

For now I will close the issue as it's gotten stale - however, if you do want to discuss this further I will reopen and we can work out some details.
