### ISSUE TITLE
Command not found Exception

### ISSUE THREAD

**Issue by lotfio** [minicli/minicli#5]
when a command is not found an exception is thrown and showing a messy information as follow:

![image](https://user-images.githubusercontent.com/18489496/82924360-838c6a00-9f7c-11ea-8d64-806545a74238.png)

catching these exceptions and handling them in a nice way will improve the user experience.

something like that : **(this is just a suggestion)** :) 

![image](https://user-images.githubusercontent.com/18489496/82924843-3957b880-9f7d-11ea-93b7-c782f6cb87b7.png)

![image](https://user-images.githubusercontent.com/18489496/82924913-4ecce280-9f7d-11ea-9b74-024a898ccae2.png)

**Comment by syntaxseed** [comment]
I fixed this in PR#7.

**Comment by erikaheidi** [comment]
I left some commands on #7. I think this output looks interesting, but it's still a bit to "dev-y" for final users (whenever you distribute your app) - maybe we need an option in the config file to set up debug to true or false.

**Comment by syntaxseed** [comment]
Handled these concerns with PR #12.
