### ISSUE TITLE
Outdated library's description?

### ISSUE THREAD

**Issue by panigrc** [minicli/minicli#55]
Hi, I wanna try out your project, cause it looks like a nice alternative to `symfony/console` .

I've noticed the following issue, the project's description is set to:  "Experimental micro CLI framework for PHP" (https://github.com/minicli/minicli/blob/main/composer.json#L4)

Is this intentional? Cause it looks to me that the project is kinda stable.

**Comment by JustSteveKing** [comment]
Hey @panigrc unfortunately Erika is busy as always! The composer description was added when she originally started the project, which at first was experimental. However, it is no longer experimental and indeed stable.

I have joined to help her keep on top of it now, so I will make sure this gets updated.
