### ISSUE TITLE
Theme setting in config has no effect (Minicli v 2)

### ISSUE THREAD

**Issue by syntaxseed** [minicli/minicli#8]
Changing the theme in the 'minicli' executable config like so:

```php
$app = new App([
    'app_path' => __DIR__ . '/app/Command',
    'theme' => 'unicorn'
]);
```

No longer has an effect.

I have to set the OutputHandler like so:

```php
$output = new \Minicli\Output\OutputHandler();
$output->registerFilter(new \Minicli\Output\Filter\ColorOutputFilter(new Minicli\Output\Theme\UnicornTheme()));
$app->setOutputHandler($output);
```

I looked into solving this... but the App class needs a nice way to parse the config value and determine if it's a theme class that exists. I worried this would make the App constructor messy.

I wasn't sure how you wanted to approach this, so I didn't make a PR. But I can work on this if you have some feedback on how you want it handled. My initial thought was a new method on App called something like parseThemeSetting(...), but wasn't sure if it belongs there.

**Comment by syntaxseed** [comment]
A working rough solution in the App constructor looks like:

```php
public function __construct(array $config = [])
    {
        $config = array_merge([
            'app_path' => __DIR__ . '/../app/Command',
        ], $config);

        $this->setSignature('./minicli help');

        $this->addService('config', new Config($config));
        $this->addService('command_registry', new CommandRegistry($this->config->app_path));

        $output = new OutputHandler();
        $themeName = '\Minicli\Output\Theme\\'.ucfirst($this->config->theme).'Theme';
        if (class_exists($themeName)){
            $output->registerFilter(new ColorOutputFilter(new $themeName()));
        }else{
            $output->registerFilter(new ColorOutputFilter());
        }
        $this->addService('printer', $output);
    }
```

**Comment by erikaheidi** [comment]
Thank you for flagging this! What I had in mind was to leave this more open to developers to create custom themes, but I can definitely see how more complicated it is now to change the theme, and it shouldn't be that way.

I like your idea, I think moving this logic to another method in the App class will be enough. At first I was worried about users not being able to use a custom CLITheme class on other namespace, but in this case they can still use the `setOutputHandler` method to use their custom class! :) 

Go for it! :dancers:

**Comment by syntaxseed** [comment]
Will do!

**Comment by syntaxseed** [comment]
I will try to have it so users can config a built-in theme like Unicorn... or a user defined theme.

Maybe a leading slash means a built in theme like:

```
$app = new App([
    'theme' => '/unicorn'
]);
```
Vs a theme in the user's project like so:
```
$app = new App([
    'theme' => 'app/themes/rainbow'
]);
```

**Comment by syntaxseed** [comment]
Created a PR #11 for this feature.

Updated readme and tests.

Handles built-in theme (Unicorn) or user-defined themes by namespace.

I tried to write a test for whether the correct theme was loaded.. .but can't get the theme from the App object.

**Comment by erikaheidi** [comment]
This one was addressed! :+1:
